Edit recipes to allow building RCU Service and SDK
ni/meta-ateccgen2 pull request #7
Opened 2021-02-25 05:48 UTC by HatsyRei

Also bumped git hash in smartracks-manifest, so bbappend recipe for Toradex linux kernel is renamed.

https://github.com/ni/smartracks-manifest/commit/0f8f4fbf08e3983a66f43bc21a6c2fc0288cddbe

2021-02-25 06:36 UTC, karhin1990 requested changes

2021-02-25 06:36 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +DEPENDS = " protobuf-native grpc grpc-native "
Double check: No RDEPEND needed?

2021-02-25 06:36 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +inherit cmake pkgconfig
Question: pkgconfig is for what purpose?

2021-02-25 06:36 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +# A hacky way to get grpc dependencies to work in order to build RCU service
Nit: Comment improvement
Perhaps can update this line to: "Workaround for grpc cross-compilation. This issue was reported in: [put the URL of someone ask this question in web]"

2021-02-25 06:36 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +# Then, manually copy five aarch64 .so files required to build RCU service to x86 sysroot
Nit: 
- Capital 'S' for RCU [S]ervice
- Can you put a comment why these .so has to copied to x86 sysroot?

2021-02-25 06:36 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +         install -m 0755 rcu-service-cpp-test-client ${D}${bindir}
We don't want the test client to be installed in RCU Image by default, because it's not needed by customer. 
It's for internal used only, so we should export it to a separate package (e.g. smartracks-tests.ipk) that available on the package feed.

2021-02-25 07:25 UTC, HatsyRei commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +inherit cmake pkgconfig
I think this is one of the things I tried in order to get gRPC to work, and it is accidentally left in there. I'll run a clean build without pkgconfig and flash the image, make sure everything works, then I'll remove it in case it is not actually required.

2021-02-25 08:46 UTC, HatsyRei commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +DEPENDS = " protobuf-native grpc grpc-native "
Yep, just clean built and flashed into SOM, can confirm that it is working. Another observation is, even without RDEPENDS, installing the ipk by itself will still cause opkg to look for gRPC and other runtime dependencies. Seems like runtime dependencies are implicitly specified somewhere in the gRPC recipes... Do you think it would be a good idea to specify RDEPENDS anyway? It does not seem to affect anything for now.

2021-02-25 10:16 UTC, karhin1990 reviewed
Will there be another PR to package rcu-service-cpp-test-client into a separate ipk?
Will be approving this PR once the RDEPENDS comment is addressed.

2021-02-25 10:16 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +DEPENDS = " protobuf-native grpc grpc-native "
I think we need to know if there is actually grpc-specific runtime libraries (you could try ld the rcu-service and see if it shows you any dependency that provided by grpc). If yes, then we need to find out which OE package provides it and add it to RPDEPENDS; else we are safe to leave it as it is.

2021-02-25 10:16 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +
Nit: Extra line

2021-02-25 10:16 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +EXTRA_OECMAKE = " \
Would be helpful to put some comment for this. Like what you previously written in the rcu-service CMakelist.

Question: Is it matters where to specify this? Do it has to be specify before "inherit cmake" so that it visible to cmake during do_compile/do_configure?

2021-02-25 10:47 UTC, HatsyRei commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +EXTRA_OECMAKE = " \
> Will there be another PR to package rcu-service-cpp-test-client into a separate ipk?
> Will be approving this PR once the RDEPENDS comment is addressed.

Yep. We can write a new recipe to package rcu-service-cpp-test-client into an ipk. It would contain the same lines used to build gRPC dependent applications, with no installation of .service or dependency on systemd. I think I can add that really soon if that is all we need to do.

2021-02-25 10:55 UTC, HatsyRei commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +EXTRA_OECMAKE = " \
> Question: Is it matters where to specify this? Do it has to be specify before "inherit cmake" so that it visible to cmake during do_compile/do_configure?

Doesn't seem like it matters. I managed to move EXTRA_OECMAKE above the inherit statement and get it to build just fine.

2021-02-26 02:02 UTC, HatsyRei commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +DEPENDS = " protobuf-native grpc grpc-native "
I managed to find this link, which says the following. Could be our case here:
https://wiki.yoctoproject.org/wiki/TipsAndTricks/Packaging_Prebuilt_Libraries

>If the precompiled binaries are not statically linked and have dependencies on other libraries, then by adding those libraries to DEPENDS the linking can be examined and the appropriate RDEPENDS automatically added.

2021-02-26 02:06 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +DEPENDS = " protobuf-native grpc grpc-native "
Cool, I'll mark this comment as Resolved. Thanks!

2021-02-26 02:10 UTC, karhin1990 commented on recipes-core/rcu-service/rcu-service_1.0.bb
> +EXTRA_OECMAKE = " \
Great, I'm going to approve this PR and please use a new PR for the tests-specific package creation. Thanks!

2021-02-26 02:11 UTC, karhin1990 approved these changes

2021-02-26 08:33 UTC, merged